Set up job
Current runner version: '2.323.0'
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250323.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250323.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250323.1
Runner Image Provisioner
  2.0.422.1
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Pages: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download immutable action package 'actions/checkout@v4'
  Version: 4.2.2
  Digest: sha256:ccb2698953eaebd21c7bf6268a94f9c26518a7e38e27e0b83c1fe1ad049819b1
  Source commit SHA: 11bd71901bbe5b1630ceea73d27597364c9af683
Download action repository 'actions/jekyll-build-pages@v1' (SHA:44a6e6beabd48582f863aeeb6cb2151cc1716697)
Download immutable action package 'actions/upload-pages-artifact@v3'
  Version: 3.0.1
  Digest: sha256:aa65de5e734350e024ca30fe125144b6260e68160e01349fc79f7e321ec35490
  Source commit SHA: 56afc609e74202658d3ffba0e8f6dda462b719fa
Getting action download info
Download immutable action package 'actions/upload-artifact@v4'
  Version: 4.6.2
  Digest: sha256:290722aa3281d5caf23d0acdc3dbeb3424786a1a01a9cc97e72f147225e37c38
  Source commit SHA: ea165f8d65b6e75b540449e92b4886f43607fa02
Complete job name: build
Pull ghcr.io/actions/jekyll-build-pages:v1.0.13
Pull down action image 'ghcr.io/actions/jekyll-build-pages:v1.0.13'
  /usr/bin/docker pull ghcr.io/actions/jekyll-build-pages:v1.0.13
  v1.0.13: Pulling from actions/jekyll-build-pages
  efc2b5ad9eec: Pulling fs layer
  165b60d1bb48: Pulling fs layer
  2a328af1ca3a: Pulling fs layer
  32b58fa44788: Pulling fs layer
  590ab93c22d2: Pulling fs layer
  26ea96c4c14c: Pulling fs layer
  bd7e451dfea1: Pulling fs layer
  c209e9dadc51: Pulling fs layer
  a4925b5c711a: Pulling fs layer
  cd9459784e3c: Pulling fs layer
  bd7e451dfea1: Waiting
  32b58fa44788: Waiting
  a4925b5c711a: Waiting
  cd9459784e3c: Waiting
  590ab93c22d2: Waiting
  26ea96c4c14c: Waiting
  c209e9dadc51: Waiting
  2a328af1ca3a: Verifying Checksum
  2a328af1ca3a: Download complete
  165b60d1bb48: Verifying Checksum
  165b60d1bb48: Download complete
  efc2b5ad9eec: Download complete
  32b58fa44788: Verifying Checksum
  32b58fa44788: Download complete
  bd7e451dfea1: Verifying Checksum
  bd7e451dfea1: Download complete
  c209e9dadc51: Verifying Checksum
  c209e9dadc51: Download complete
  a4925b5c711a: Verifying Checksum
  a4925b5c711a: Download complete
  cd9459784e3c: Verifying Checksum
  cd9459784e3c: Download complete
  26ea96c4c14c: Verifying Checksum
  26ea96c4c14c: Download complete
  590ab93c22d2: Download complete
  efc2b5ad9eec: Pull complete
  165b60d1bb48: Pull complete
  2a328af1ca3a: Pull complete
  32b58fa44788: Pull complete
  590ab93c22d2: Pull complete
  26ea96c4c14c: Pull complete
  bd7e451dfea1: Pull complete
  c209e9dadc51: Pull complete
  a4925b5c711a: Pull complete
  cd9459784e3c: Pull complete
  Digest: sha256:6791ebfd912185ed59bfb5fb102664fa872496b79f87ff8b9cfba292a7345041
  Status: Downloaded newer image for ghcr.io/actions/jekyll-build-pages:v1.0.13
  ghcr.io/actions/jekyll-build-pages:v1.0.13

Checkout
Run actions/checkout@v4
  with:
    ref: main
    submodules: recursive
    repository: smuyun/kenpark76.github.io
    token: ***
    ssh-strict: true
    ssh-user: git
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    set-safe-directory: true
Syncing repository: smuyun/kenpark76.github.io
Getting Git version info
  Working directory is '/home/runner/work/smuyun.github.io/kenpark76.github.io'
  /usr/bin/git version
  git version 2.49.0
Temporarily overriding HOME='/home/runner/work/_temp/67dcb598-577a-45ac-b586-66c639ba91fa' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/smuyun.github.io/kenpark76.github.io
Deleting the contents of '/home/runner/work/smuyun.github.io/kenpark76.github.io'
Initializing the repository
  /usr/bin/git init /home/runner/work/smuyun.github.io/kenpark76.github.io
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint:
  hint: 	git config --global init.defaultBranch <name>
  hint:
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint:
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/smuyun.github.io/kenpark76.github.io/.git/
  /usr/bin/git remote add origin https://github.com/smuyun/kenpark76.github.io
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  From https://github.com/smuyun/kenpark76.github.io
   * [new branch]      main       -> origin/main
Determining the checkout info
  /usr/bin/git branch --list --remote origin/main
    origin/main
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
Setting up auth for fetching submodules
  /usr/bin/git config --global http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --global --unset-all url.https://github.com/.insteadOf
  /usr/bin/git config --global --add url.https://github.com/.insteadOf git@github.com:
  /usr/bin/git config --global --add url.https://github.com/.insteadOf org-102659551@github.com:
Fetching submodules
  /usr/bin/git submodule sync --recursive
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
  /usr/bin/git submodule foreach --recursive git config --local gc.auto 0
Persisting credentials for submodules
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'url\.https\:\/\/github\.com\/\.insteadOf' && git config --local --unset-all 'url.https://github.com/.insteadOf' || :"
  /usr/bin/git submodule foreach --recursive sh -c "git config --local 'http.https://github.com/.extraheader' 'AUTHORIZATION: basic ***' && git config --local --show-origin --name-only --get-regexp remote.origin.url"
  /usr/bin/git submodule foreach --recursive git config --local --add 'url.https://github.com/.insteadOf' 'git@github.com:'
  /usr/bin/git submodule foreach --recursive git config --local --add 'url.https://github.com/.insteadOf' 'org-102659551@github.com:'
/usr/bin/git log -1 --format=%H
44e8e22656ea28278827a0e466abec315565927d
Build with Jekyll
Run actions/jekyll-build-pages@v1
  with:
    source: .
    destination: ./_site
    future: false
    build_revision: 44e8e22656ea28278827a0e466abec315565927d
    verbose: true
    token: ***
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1013_20713a --label 1e8d5e --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/smuyun.github.io/kenpark76.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.13
Configuration file: none
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Logging at level: debug
      GitHub Pages: github-pages v232
      GitHub Pages: jekyll v3.10.0
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /github/workspace/.
       Destination: /github/workspace/./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.000199282 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.001680126 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 5.099e-06 seconds.
   GitHub Metadata: Generating for smuyun/kenpark76.github.io
   GitHub Metadata: Calling @client.pages("smuyun/kenpark76.github.io", {})
        Generating: JekyllRelativeLinks::Generator finished in 0.150989708 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.000136094 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 4.4954e-05 seconds.
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
         Rendering: README.md
  Pre-Render Hooks: README.md
  Rendering Markup: README.md
         Requiring: kramdown-parser-gfm
  Rendering Layout: README.md
     Layout source: theme
   GitHub Metadata: Calling @client.organization("kenpark76")
   GitHub Metadata: Calling @client.user("kenpark76")
   GitHub Metadata: Calling @client.repository("smuyun/kenpark76.github.io", {:accept=>"application/vnd.github.drax-preview+json"})
           Writing: /github/workspace/_site/assets/css/style.css
           Writing: /github/workspace/_site/index.html
                    done in 1.564 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Upload artifact
Run actions/upload-pages-artifact@v3
  with:
    path: ./_site
    name: github-pages
    retention-days: 1
Run echo ::group::Archive artifact
  echo ::group::Archive artifact
  tar \
    --dereference --hard-dereference \
    --directory "$INPUT_PATH" \
    -cvf "$RUNNER_TEMP/artifact.tar" \
    --exclude=.git \
    --exclude=.github \
    .
  echo ::endgroup::
  shell: /usr/bin/sh -e {0}
  env:
    INPUT_PATH: ./_site
Archive artifact
  ./
  ./koreatv.json
  ./message/
  ./message/message_old.txt
  ./message/message_zh_old.txt
  ./message/message_ko_old.txt
  ./index.html
  ./assets/
  ./assets/css/
  ./assets/css/style.css
  ./README.md
  ./PJYTV.apk
  ./koreatvEPG.xml
  ./banner0.png
  ./test.json
  ./test/
  ./test/test.json
  ./test/live.txt
  ./koreatv.txt
  ./logo/
  ./logo/海南卫视.png
  ./logo/四川卫视.png
  ./logo/CCTV-12 社会与法.png
  ./logo/三沙卫视.png
  ./logo/CCTV-17 农业农村.png
  ./logo/重庆卫视.png
  ./logo/河北卫视.png
  ./logo/山东卫视.png
  ./logo/CCTV-6 电影.png
  ./logo/凤凰香港.png
  ./logo/YTN.png
  ./logo/青海卫视.png
  ./logo/SBS M.png
  ./logo/广西卫视.png
  ./logo/CHC动作电影.png
  ./logo/陕西卫视.png
  ./logo/KBS Kids.png
  ./logo/KBS Drama.png
  ./logo/延边1台.png
  ./logo/KBS Story.png
  ./logo/CCTV-13 新闻.png
  ./logo/tvN.png
  ./logo/TBS TV.jpeg
  ./logo/JTBC2.png
  ./logo/CCTV-14 少儿.png
  ./logo/CCTV-9 纪录.png
  ./logo/江西卫视.png
  ./logo/Mnet.png
  ./logo/SBS funE.png
  ./logo/방송대학TV.png
  ./logo/北京卫视.png
  ./logo/宁夏卫视.png
  ./logo/LIFETIME.png
  ./logo/兵团卫视.png
  ./logo/농협TV.png
  ./logo/YTN2.png
  ./logo/吉林卫视.png
  ./logo/KBS2.png
  ./logo/SBS Biz.png
  ./logo/贵州卫视.png
  ./logo/CCTV-4 中文国际.png
  ./logo/MBN 플러스.png
  ./logo/ABN.png
  ./logo/河南卫视.png
  ./logo/tvN STORY.png
  ./logo/安徽卫视.png
  ./logo/天津卫视.png
  ./logo/上视东方影视.png
  ./logo/YTN사이언스.png
  ./logo/국회방송(NATV).png
  ./logo/CCTV-3 综艺.png
  ./logo/浙江卫视.png
  ./logo/东方卫视.png
  ./logo/MBC Every1.png
  ./logo/투니버스.png
  ./logo/채널A플러스.png
  ./logo/广东卫视.png
  ./logo/MBN.png
  ./logo/CCTV-16 奥林匹克.png
  ./logo/CHC家庭影院.png
  ./logo/tvN SHOW.png
  ./logo/辽宁卫视.png
  ./logo/CCTV-2 财经.png
  ./logo/SBS.png
  ./logo/아리랑 TV.png
  ./logo/tvN DRAMA.png
  ./logo/凤凰中文.png
  ./logo/MBC Dramanet.png
  ./logo/SBSGOLF.png
  ./logo/CCTV-15 音乐.png
  ./logo/内蒙古卫视.png
  ./logo/五星体育.png
  ./logo/히스토리.png
  ./logo/CCTV-5 体育.png
  ./logo/KBS뉴스.png
  ./logo/凤凰资讯.png
  ./logo/MBC M.png
  ./logo/EBS2.png
  ./logo/MBC ON.png
  ./logo/新疆卫视.png
  ./logo/延边2台.png
  ./logo/KBS Joy.png
  ./logo/MBC NET.png
  ./logo/CCTV-10 科教.png
  ./logo/CCTV-8 电视剧.png
  ./logo/JTBC.png
  ./logo/延边朝鲜语.png
  ./logo/西藏卫视.png
  ./logo/연합뉴스TV.png
  ./logo/EBS1.png
  ./logo/湖南卫视.png
  ./logo/채널A.png
  ./logo/JTBC4.png
  ./logo/KBS WORLD.png
  ./logo/延边2台(汉语综合).png
  ./logo/MBC.png
  ./logo/EBS PLUS1.png
  ./logo/EBS PLUS2.png
  ./logo/CCTV-7 国防军事.png
  ./logo/延边卫视(HD).png
  ./logo/TV CHOSUN 2.png
  ./logo/애니맥스.png
  ./logo/深圳卫视.png
  ./logo/CCTV-11 戏曲.png
  ./logo/국민방송.png
  ./logo/甘肃卫视.png
  ./logo/KBS LIFE.png
  ./logo/东南卫视.png
  ./logo/중화tv.png
  ./logo/cctv-5+体育赛事.png
  ./logo/anibox.png
  ./logo/延边卫视.png
  ./logo/山西卫视.png
  ./logo/湖北卫视.png
  ./logo/ebs English.png
  ./logo/江苏卫视.png
  ./logo/sbs plus.png
  ./logo/香港卫视.png
  ./logo/chc高清电影.png
  ./logo/延边1台（朝鲜语综合）.png
  ./logo/tvbs.png
  ./logo/kbs1.png
  ./logo/台视新闻台.png
  ./logo/民视新闻台.png
  ./logo/cctv-1综合.png
  ./logo/newtv超级电影.png
  ./logo/tv chosun.png
  ./logo/문화유산채널.png
  ./logo/黑龙江卫视.png
  ./logo/云南卫视.png
运行操作/upload-artifact@v4
  和：
    姓名：github页面
    小路：/home/runner/work/_temp/artifact.tar
    保留日：1
    如果不是文件：错误
    压缩级别：6
    覆盖：false
    包括隐藏的文件：false
有了提供的路径，将有1个文件上传
文物名称有效！
根目录输入有效！
开始将人工制品内容上传到斑点存储
上传字节8388608
上传字节12958676
完成将工件内容上传到斑点存储！
SHA256上传人工ZIP的摘要是B5CA274E7CB314354D89B25EC6D54EE81A29714F29B3A88888884D576E4F76E4F76E4F76E4F7E4F7E21872888
最终确定工件上传
trifact github-pages.zip成功完成。工件ID 2879773083
文物github 页面已成功上传！最终尺寸为12958676字节。工件ID是2879773083
伪影下载URL ：人工下载url：https：//github.com/smuyun/kenpark76.github.io/actions/runs/14255799526/artifacts/2877977777777773083 ： //github.com/smuyun/kenpark76.github.io/actions/runs/14255799526/artifacts/28797773083
结帐
邮政工作清理。
/usr/bin/git版本
GIT版本2.49.0
在进行全局GIT配置更改之前'/home/runner/work/_temp/5a68e387-8393-4407-a2c8-f8a525aade7f' before making global git config changes
将存储库目录添加到临时git全局配置作为安全目录
/usr/bin/git config -global -global -add safe.directory/home/runner/work/smuyun.github.io/kenpark76.github.io
/usr/bin/git config-local-name-lly-get-regexp core \ .sshcommand
/usr/bin/git subsodule for-erach-recursive sh -c“ git config  -  local-name-name-name-get-regexp'core \ .sshcommand'&& git config-git config  -  local-local-unset-als all'core.sshcommand'||：”"git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config-local -name-name-get-regexp http \ .https \：\/\/github \ .com \ .com \ .com \/\/\。
http.https：//github.com/.extraheader
/usr/bin/git config-local-unset-all http.https：//github.com/.extraheader
/usr/bin/git suppodule for-erach-recursive sh -c“ git config  -  local-name-name-name-get-regexp'http \ .https \ .https \：\/\/\/github \ .com \ .com \ .com \ .com \ \ \/\'http.https：///github.com/.extraheader '\/\。
完成工作
清理孤儿流程
